spring.application.name=environment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/devspace_environment
spring.datasource.username=devspace
spring.datasource.password=devspace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086
