spring.application.name=login-service

server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5432/devspace_login
spring.datasource.username=devspace
spring.datasource.password=devspace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

devspace.jwt.secret=VGhpc0lzQURldlNwYWNlU2VjdXJlSldUU2lnbmluZ0tleUZvckRldlNwYWNlMjAyNg==
devspace.jwt.expiration-ms=86400000