spring.application.name=provisioning-service
server.port=8088
devspace.services.environment.url=http://localhost:8086
devspace.kubernetes.mock=true
devspace.ingress.base-url=http://devspace.local

devspace.internal.api-key=${DEVSPACE_INTERNAL_API_KEY:devspace-internal-secret}
