spring.application.name=api-gateway

server.port=8080

devspace.jwt.secret=VGhpc0lzQURldlNwYWNlU2VjdXJlSldUU2lnbmluZ0tleUZvckRldlNwYWNlMjAyNg==

# Environment Service
spring.cloud.gateway.server.webflux.routes[0].id=environment-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/environments/**


# Template Service
spring.cloud.gateway.server.webflux.routes[1].id=template-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/templates/**

# Login Service
spring.cloud.gateway.server.webflux.routes[3].id=login-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8089
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/auth/**

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always