spring.application.name=api-gateway

server.port=8080


# Environment Service
spring.cloud.gateway.server.webflux.routes[0].id=environment-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/environments/**


# Template Service
spring.cloud.gateway.server.webflux.routes[1].id=template-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/templates/**


# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always